name: 'build latest'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours

jobs:
  get_versions:
    runs-on: ubuntu-latest
    env:
      MC_DOWNLOAD_PAGE: "https://www.minecraft.net/en-us/download/server/bedrock"
      CURL_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"
    outputs:
      latest_version: ${{ steps.latest_version.outputs.latest_version }}
      latest_download_url: ${{ steps.latest_version.outputs.latest_download_url }}
      self_version: ${{ steps.self_version.outputs.self_version }}
    steps:
      - name: latest version
        id: latest_version
        run: |
          MC_DOWNLOAD_PAGE_CONTENT=$(curl -s -L -A "${CURL_USER_AGENT}" "${MC_DOWNLOAD_PAGE}")
          echo latest_download_url=$(echo "${MC_DOWNLOAD_PAGE_CONTENT}" | grep "linux/bedrock-server-" | egrep -o 'https?://[^" ]+') >> $GITHUB_OUTPUT
          echo latest_version=$(echo "${MC_DOWNLOAD_PAGE_CONTENT}" | grep "linux/bedrock-server-" | egrep -o 'https?://[^" ]+' | xargs basename -s ".zip" | sed -En 's#bedrock-server-([0-9.]+)#\1#p') >> $GITHUB_OUTPUT

      - name: show latest download url
        run: |
          echo ${{ steps.latest_version.outputs.latest_download_url }}

      - name: show latest version
        run: |
          echo ${{ steps.latest_version.outputs.latest_version }}

      - name: self version
        id: self_version
        run: |
          docker pull ghcr.io/${{ github.repository }}
          echo self_version=$(docker inspect docker.io/marctv/minecraft-bedrock-server:latest --format '{{ index .Config.Labels "org.opencontainers.image.version"}}') >> $GITHUB_OUTPUT

      - name: show self version
        run: |
          echo ${{ steps.self_version.outputs.self_version }}

  trigger_build:
    runs-on: ubuntu-latest
    needs: get_versions
    permissions: write-all
    name: trigger build for ${{ needs.get_versions.outputs.latest_version }}
    if: needs.get_versions.outputs.latest_version != needs.get_versions.outputs.self_version || github.event_name == 'workflow_dispatch'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: build_version
          # todo download_url from latest_version
          client-payload: '{"download_url": "${{ needs.get_versions.outputs.latest_download_url }}", "is_latest": "yes"}'
