name: Build and push

on: 
  push:
  schedule:
  - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update Readme.md and description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_HUB_USERNAME }}
        pass: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        slug: marctv/minecraft-bedrock-server
        readme: ./README.md
        description: Minecraft Bedrock Server 1.19 for Windows, iOS, Android, PlayStation and Xbox — Starts fast, runs stable and is always up-to-date. 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username:  ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: marctv/minecraft-bedrock-server:latest
